apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gist-api.fullname" . }}
  labels:
    app.kebernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: 'backend'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kebernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kebernetes.io/name: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
