apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app.kebernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: 'helm'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kebernetes.io/name: {{ .Values.name }}
